[package]
name = "p2p-node-handshake"
version = "0.1.0"
edition = "2021"


[dependencies]
cert-manager = "0.0.11"
protobuf = "3"
rustls = { version = "0.21.5", features = ["dangerous_configuration"] }
tokio = { version = "1.35.0", features = ["full"] }

[build-dependencies]
protobuf-codegen = "3"
